### ISSUE TITLE
Is it possible to generalise it for Text as well?

### ISSUE THREAD

**Issue by adinapoli** [nikita-volkov/bytestring-tree-builder#2]
Hey @nikita-volkov !

This is more of a curiosity than a real need, but I was just wondering:

* if there is something structural which prevents this package to be extended for (strict?) `Text` as well
* if it will make sense in the first place
* If the performances would be good enough to even bother

Case in question is that I was browsing through the source code of [Katip](http://hackage.haskell.org/package/katip), and I was curious if some perf gain could be gained to replace the `Data.Text.Lazy.Builder` with a variant of this package.

Thanks!

Alfredo

**Comment by nikita-volkov** [comment]
It just so happens that I've actually just released such a library: https://hackage.haskell.org/package/text-builder. I haven't heavily tested it in use yet though.

**Comment by adinapoli** [comment]
Wow, talking about timing! :)

Happy to play around with it and do the guinea pig :D

Thanks!

Alfredo
